FROM debian:11-slim
RUN apt-get update && apt-get install -y \
    wget \
    gnupg2 \
    curl \
    default-mysql-client \
    lsb-release \
    groff \
	less \
	unzip \
 && curl "https://awscli.amazonaws.com/awscli-exe-linux-x86_64.zip" -o "awscliv2.zip" \
 && unzip awscliv2.zip \
 && ./aws/install \
 && sh -c 'echo "deb http://apt.postgresql.org/pub/repos/apt $(lsb_release -cs)-pgdg main" > /etc/apt/sources.list.d/pgdg.list' \
 && wget --quiet -O - https://www.postgresql.org/media/keys/ACCC4CF8.asc | apt-key add - \
 && apt-get update && apt-get install -y \
    postgresql \
 && apt-get clean && rm -rf /var/lib/apt/lists/* /tmp/* /var/tmp/*

COPY function.sh /function.sh
RUN chmod +x /function.sh
ENTRYPOINT ["/function.sh"]